name: CI Pipeline (DOC1)

on:
  # Manually trigger workflow runs
  workflow_dispatch:

  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

jobs:
  build:
    name: My First Pipeline
    runs-on: ubuntu-latest

    steps:
      # Check out your repository
      - uses: actions/checkout@v4

      # Run a simple script
      - name: Run a one-line script
        run: echo "Continuous Integration"